### ISSUE TITLE
Lauching mybinder fails

### ISSUE THREAD

**Issue by andersy005** [Quansight/numba-xnd#14]
There seems to be an issue with https://github.com/Quansight/numba-xnd/blob/master/structinfo_config.py#L16 on mybinder. 

and here is the output from mybinder build logs

```python
Using /srv/conda/lib/python3.6/site-packages
Finished processing dependencies for numba==0+unknown
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import structinfo_config as xinfo_config
  File "/home/jovyan/structinfo_config.py", line 16, in <module>
    PREFIX = os.environ["CONDA_PREFIX"]
  File "/srv/conda/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CONDA_PREFIX'
```

**Comment by saulshanabrook** [comment]
Yeah I had seen those errors... I will get that working.

**Comment by andersy005** [comment]
It looks like mybinder doesn't create the specified environment in environment.yml.
It just updates the root environment using `environment.yml`

```bash
Step 30/39 : RUN conda env update -n root -f "environment.yml" && conda clean -tipsy && conda list -n root
````

I believe this explains why `$CONDA_PREFIX` environment variable is not set.

**Comment by saulshanabrook** [comment]
Interesting... If you know of any fixes, they would be much appreaciated.

**Comment by andersy005** [comment]
I am going to look into it. I will submit a PR once I know how to fix the issue

**Comment by saulshanabrook** [comment]
Thank you, much appreciated.
